print("Hola empresa soy JUAN Jose el commiter")
print("Hola soy Miguel")
print("Mauricio Andrés Parra Colorado, Junior")
print("Juan Guillermo Mejía Correa - Desarrollador Full Stack")
print("Mauricio Andrés Parra Colorado, Junior")
print("Hola soy Andres Agudelo y soy el developer full stack")
